### ISSUE TITLE
Checkpoint 2 - Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [nikofenev/ScheduleGenerator#4]
Looks like you have a really good start!

- [ ] DB - looks like start and end times are stored as ints? Does that mean only "whole" hours are used?
- [ ] Take a look at the Generic Dao info in #hibernate in slack.  This can save you quite a bit of Dao coding.
- [ ] What is DropDownWithAllHours used for? Seems like this could be something that would just exist on the front end, so I think maybe I don't understand the intent.
- [ ] Have you explored Google calendar much yet? I'm curious what functionality you are targeting for the web service.

**Comment by nikofenev** [comment]
*   DB - I will store the availability as whole hours, because I think it is easier to select from drop down list, and actual shifts will be decimal.
*  That is my plan for today, to implement the generic Dao.
*  DropDownWithAllHours I use only for the front end, because I don't won't to type the <select> tag with <option> with all hours 7 times or more. I don't know if that is a good design? let me know if I could do something else.
*  I Looked up Google calendar documentation, and after I complete the issues above I will spend time on it.
*

**Comment by pawaitemadisoncollege** [comment]
I think if you were writing a custom tag that depended on some data from you system, doing the time picker in java might make sense.

Maybe a jquery time picker would be appropriate? Here is just one option, there are many: 
http://jonthornton.github.io/jquery-timepicker/

**Comment by nikofenev** [comment]
Cool. I already use jquery for the week picker, I will do the same for the hours. Thanks 🙏
